kind: Deployment
apiVersion: apps/v1
metadata:
  name: app5
  namespace: cpd-support-my-first-ns
  uid: 9473b011-70f0-4097-bd95-65673247258d
  resourceVersion: '1868377115'
  generation: 3
  creationTimestamp: '2022-09-15T08:18:17Z'
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app5
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app5
        version: 2022-09-15-08.18.17
    spec:
      containers:
        - name: app3
          image: 'registry-jpe2.r-local.net/dockerhub/library/busybox:latest'
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - sleep 30s
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: tenant-pod-root
      serviceAccount: tenant-pod-root
      automountServiceAccountToken: true
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-09-15T08:18:20Z'
      lastTransitionTime: '2022-09-15T08:18:17Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "app-5b987994f" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-09-15T08:21:44Z'
      lastTransitionTime: '2022-09-15T08:21:44Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.

